# Generated by Django 2.1.4 on 2019-01-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20190102_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Tutor'), (3, 'Hijo(a)'), (4, 'Staff'), (5, 'Supervisor'), (6, 'Business')], default=1, verbose_name='Rol'),
        ),
    ]
