# Generated by Django 2.1.4 on 2019-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20190102_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
