# Generated by Django 2.1.4 on 2019-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20190411_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Usuario'), (3, 'Staff')], default=1, verbose_name='Rol'),
        ),
    ]
